CREATE TABLE [dbo].[Log]
(
	[Id] INT NOT NULL CONSTRAINT [PK_Log] PRIMARY KEY IDENTITY(1, 1),
	[LogLevelId] INT NOT NULL CONSTRAINT [FK_LogLevel_Log] FOREIGN KEY REFERENCES LogLevel(Id),
	[Message] NVARCHAR(MAX) NOT NULL,
	[ClassName] NVARCHAR(MAX) NOT NULL,
	[MethodName] NVARCHAR(MAX) NOT NULL,
	[StackTrace] NVARCHAR(MAX) NULL,
	[CreatedDateUTC] DATETIME NOT NULL CONSTRAINT [DF_CreatedDateUTC] DEFAULT (GETUTCDATE())
)
